spring.config.import=optional:secrets.properties
spring.application.name=proxmox-notifier
spring.threads.virtual.enabled=true

logging.level.com.pedrovisk.*=INFO
feign.client.config.default.loggerLevel=basic

feign.httpclient.enabled=false
feign.okhttp.enabled=true
feign.httpclient.disableSslValidation=true

#Set this to true if you want to disable SSL certificate validation
feign.client.insecure=true

spring.cloud.openfeign.client.config.proxmox.requestInterceptor=com.pedrovisk.proxmox.api.ProxmoxRequestInterceptor

#spring.docker.compose.lifecycle-management=none

proxmox.api-url=${PROXMOX_API_URL:https://localhost:8006/}
proxmox.auth-token=${PROXMOX_AUTH_TOKEN}

#cron.expression=0 */1 * * * *
update.frequency.node-status=${UPDATE_FREQUENCY_NODE_STATUS:60000}
update.frequency.firewall-log=${UPDATE_FREQUENCY_FIREWALL:300000000}
update.frequency.temperature=${UPDATE_FREQUENCY_TEMPERATURE:30000}

threshold.configuration.free-memory=100
threshold.configuration.free-swap=100
threshold.configuration.free-rootfs=100

firewall-log.configuration.enable-load-everything=false

management.endpoints.web.exposure.include=*
management.endpoints.health.show-details=always
management.endpoints.health.enabled=true
management.tracing.sampling.probability=1.0
management.metrics.web.server.auto-time-requests=true

spring.mail.host=${SMTP_HOST:smtp.gmail.com}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USER:user}
spring.mail.password=${SMTP_PASSWORD:password}
spring.mail.properties.mail.smtp.auth=${SMTP_AUTH_NEEDED:true}
spring.mail.properties.mail.smtp.starttls.enable=${SMTP_TTLS_ENABLED:true}

telegram.bot.token=${TELEGRAM_TOKEN:token}
telegram.bot.chat-id=${TELEGRAM_CHAT_ID:123}
telegram.bot.api-url=${TELEGRAM_API_URL:https://api.telegram.org}
#TODO Check if this file being in tmp after deleted will impact the functionality of the bot
telegram.bot.db-path=${TELEGRAM_BOT_DB_PATH:\\config\\botdb}

ssh.configuration.username=${PROXMOX_SSH_USER:user}
ssh.configuration.password=${PROXMOX_SSH_PASSWORD:password}
ssh.configuration.host=${PROXMOX_SSH_HOST:192.168.0.10}
ssh.configuration.port=${PROXMOX_SSH_PORT:22}

proxmox.configuration-file-path=${CONFIGURATION_FILE_PATH:file:\\config\\config.json}

#SERVER_TOMCAT_ACCEPT_COUNT=3
#SERVER_TOMCAT_MAX_CONNECTIONS=3
#SERVER_TOMCAT_THREADS_MAX=3
#SERVER_TOMCAT_THREADS_MIN_SPARE=1
#SPRING_MAIN_LAZY_INITIALIZATION=true
spring.main.web-application-type=NONE
spring.main.keep-alive=true

notification.email.enabled=true
notification.telegram.enabled=true
